// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class survey_metric_displayWeekMappedToProgramDayItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(survey_metric_displayWeekMappedToProgramDayItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201903012204023_survey_metric_displayWeekMappedToProgramDayItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
